# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-UITableView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-UITableView

  target 'RxSwift-UITableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-UITableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'


end
